### PR TITLE
Milestone 8: Add mobile menu

### PR DESCRIPTION
**Pull request by pasytchangwa**
## Adding Mobile Menu

The following was done :

- Added JavaScript linters
- Added app.js file
- Updated index,HTML file for mobile menu
- Updated styles.css file for mobile menu

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi @pasytchangwa  and @elmar8287 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please make sure to set up the [javascript linters](https://github.com/microverseinc/linters-config/tree/master/javascript) correctly, the file `eslintrc.json` is supposed to start with a `.` to be `.eslintrc.json`. Kindly fix it, make sure that all the ESlint linters are passing in the PR, then submit again!

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi @pasytchangwa and @elmar8287 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

Great job making the ESlint set up. 💪 However, there is still one thing left to do!

- Please fix the linters' errors!


_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Review by Shaher-11 — CHANGES_REQUESTED** [review]
#### Hello @pasytchangwa,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Kindly style the links as the given design shown in the screenshot below:point_down:

#### Your Project
wrong1

#### Original Design
right


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

**Review by DeliceLydia — APPROVED** [review]
# Congratulations! 🎉 🎉 

Hi @pasytchangwa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
